import "./globals.css";
import { Footer, Header, Sidebar } from "@/components";
import { Nunito } from "next/font/google";
import clsx from "clsx";
import Providers from "./providers";

const inter = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "GPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={clsx(inter.className, "")}>
        <Providers>
          <div className="h-screen grid grid-rows-layout">
            <Header />
            <main className="bg-gray-100 grid grid-cols-main">
              <Sidebar />
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
